# Generated by Django 5.0.4 on 2024-04-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('line', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
                ('width_neighbour1', models.CharField(max_length=50)),
                ('longitude_neighbour1', models.CharField(max_length=50)),
                ('width_neighbour2', models.CharField(max_length=50)),
                ('longitude_neighbour2', models.CharField(max_length=50)),
                ('is_favourite', models.BooleanField(default=False)),
                ('alarm', models.CharField(max_length=100)),
            ],
        ),
    ]
