# Generated by Django 5.0.4 on 2024-04-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseApplication', '0003_rename_order_stationmodel_station_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationmodel',
            name='alarm',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stationmodel',
            name='is_favourite',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='stationmodel',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stationmodel',
            name='line',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stationmodel',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stationmodel',
            name='longitude_neighbour1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stationmodel',
            name='longitude_neighbour2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stationmodel',
            name='width_neighbour1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stationmodel',
            name='width_neighbour2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
